window.PRODUCTS = [
  {
    "no": 1,
    "name": "2,6-Dichloro-5-fluoro-3-pyridinecarbonitrile",
    "cas": "82671-02-1",
    "purity": "99%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "20 t",
    "status": "In stock",
    "price": "RMB 550,000/t",
    "cid": 2733849,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2733849/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/2733849",
    "properties": {
      "formula": "C6HCl2FN2",
      "molecularWeight": "190.99",
      "exactMass": "189.9500816",
      "iupac": "2,6-dichloro-5-fluoropyridine-3-carbonitrile",
      "smiles": "C1=C(C(=NC(=C1F)Cl)Cl)C#N",
      "xlogp": 2.6,
      "tpsa": 36.7,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 0,
      "heavyAtomCount": 11,
      "complexity": 190
    }
  },
  {
    "no": 2,
    "name": "2,6-Dichloro-5-fluoronicotinic acid",
    "cas": "82671-06-5",
    "purity": "98%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "10 t",
    "status": "In stock",
    "price": "RMB 720,000/t",
    "cid": 2733659,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2733659/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/2733659",
    "properties": {
      "formula": "C6H2Cl2FNO2",
      "molecularWeight": "209.99",
      "exactMass": "208.9446619",
      "iupac": "2,6-dichloro-5-fluoropyridine-3-carboxylic acid",
      "smiles": "C1=C(C(=NC(=C1F)Cl)Cl)C(=O)O",
      "xlogp": 2.4,
      "tpsa": 50.2,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 1,
      "heavyAtomCount": 12,
      "complexity": 192
    }
  },
  {
    "no": 3,
    "name": "2,6-Dichloro-5-fluoronicotinamide",
    "cas": "113237-20-0",
    "purity": "99%",
    "appearance": "Off-white powder",
    "physicalState": "solid",
    "capacity": "10 t",
    "status": "In stock",
    "price": "RMB 1,000,000/t",
    "cid": 2774022,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2774022/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/2774022",
    "properties": {
      "formula": "C6H3Cl2FN2O",
      "molecularWeight": "209.00",
      "exactMass": "207.9606463",
      "iupac": "2,6-dichloro-5-fluoropyridine-3-carboxamide",
      "smiles": "C1=C(C(=NC(=C1F)Cl)Cl)C(=O)N",
      "xlogp": 1.8,
      "tpsa": 56,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 1,
      "heavyAtomCount": 12,
      "complexity": 192
    }
  },
  {
    "no": 4,
    "name": "Ethyl 2,6-dichloro-5-fluoro-beta-oxo-3-pyridinepropionate",
    "cas": "96568-04-6",
    "purity": "99%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "10 t",
    "status": "In stock",
    "price": "RMB 820,000/t",
    "cid": 2733708,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2733708/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/2733708",
    "properties": {
      "formula": "C10H8Cl2FNO3",
      "molecularWeight": "280.08",
      "exactMass": "278.9865267",
      "iupac": "ethyl 3-(2,6-dichloro-5-fluoro-3-pyridinyl)-3-oxopropanoate",
      "smiles": "CCOC(=O)CC(=O)C1=CC(=C(N=C1Cl)Cl)F",
      "xlogp": 2.9,
      "tpsa": 56.3,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 5,
      "rotatableBondCount": 5,
      "heavyAtomCount": 17,
      "complexity": 303
    }
  },
  {
    "no": 5,
    "name": "Methyl 2,6-dichloro-5-fluoronicotinate",
    "cas": "189281-66-1",
    "purity": "99%",
    "appearance": "Pale yellow liquid",
    "physicalState": "liquid",
    "capacity": "10 t",
    "status": "Made-to-order",
    "price": "RMB 1,000,000/t",
    "cid": 2775354,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2775354/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/2775354",
    "properties": {
      "formula": "C7H4Cl2FNO2",
      "molecularWeight": "224.01",
      "exactMass": "222.9603119",
      "iupac": "methyl 2,6-dichloro-5-fluoropyridine-3-carboxylate",
      "smiles": "COC(=O)C1=CC(=C(N=C1Cl)Cl)F",
      "xlogp": 2.7,
      "tpsa": 39.2,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 2,
      "heavyAtomCount": 13,
      "complexity": 205
    }
  },
  {
    "no": 6,
    "name": "Ethyl 2,6-dichloro-5-fluoropyridine-3-carboxylate",
    "cas": "82671-03-2",
    "purity": "99%",
    "appearance": "Pale yellow liquid",
    "physicalState": "liquid",
    "capacity": "10 t",
    "status": "Made-to-order",
    "price": "RMB 950,000/t",
    "cid": 13210747,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/13210747/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/13210747",
    "properties": {
      "formula": "C8H6Cl2FNO2",
      "molecularWeight": "238.04",
      "exactMass": "236.9759620",
      "iupac": "ethyl 2,6-dichloro-5-fluoropyridine-3-carboxylate",
      "smiles": "CCOC(=O)C1=CC(=C(N=C1Cl)Cl)F",
      "xlogp": 3.1,
      "tpsa": 39.2,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 3,
      "heavyAtomCount": 14,
      "complexity": 218
    }
  },
  {
    "no": 7,
    "name": "5-Fluoronicotinic Acid",
    "cas": "402-66-4",
    "purity": "99%",
    "appearance": "Off-white powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "In stock",
    "price": "RMB 4,000,000/t",
    "cid": 120232,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/120232/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/120232",
    "properties": {
      "formula": "C6H4FNO2",
      "molecularWeight": "141.10",
      "exactMass": "141.02260653",
      "iupac": "5-fluoropyridine-3-carboxylic acid",
      "smiles": "C1=C(C=NC=C1F)C(=O)O",
      "xlogp": 0.5,
      "tpsa": 50.2,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 1,
      "heavyAtomCount": 10,
      "complexity": 140
    }
  },
  {
    "no": 8,
    "name": "5-Fluoronicotinamide",
    "cas": "70-58-6",
    "purity": "99%",
    "appearance": "By inquiry",
    "physicalState": "inquiry",
    "capacity": "By inquiry",
    "status": "Made-to-order",
    "price": "About RMB 3,700,000/t",
    "cid": 101264,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/101264/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/101264",
    "properties": {
      "formula": "C6H5FN2O",
      "molecularWeight": "140.11",
      "exactMass": "140.03859095",
      "iupac": "5-fluoropyridine-3-carboxamide",
      "smiles": "C1=C(C=NC=C1F)C(=O)N",
      "xlogp": -0.2,
      "tpsa": 56,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 1,
      "heavyAtomCount": 10,
      "complexity": 140
    }
  },
  {
    "no": 9,
    "name": "5-Fluoro-3-pyridinamine",
    "cas": "210169-05-4",
    "purity": "99%",
    "appearance": "By inquiry",
    "physicalState": "inquiry",
    "capacity": "By inquiry",
    "status": "Made-to-order",
    "price": "About RMB 2,600,000/t",
    "cid": 574450,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/574450/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/574450",
    "properties": {
      "formula": "C5H5FN2",
      "molecularWeight": "112.10",
      "exactMass": "112.04367633",
      "iupac": "5-fluoropyridin-3-amine",
      "smiles": "C1=C(C=NC=C1F)N",
      "xlogp": 0.3,
      "tpsa": 38.9,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 0,
      "heavyAtomCount": 8,
      "complexity": 76
    }
  },
  {
    "no": 10,
    "name": "2-Chloro-5-fluoropyridine-4-carboxylic acid",
    "cas": "884494-74-0",
    "purity": "99%",
    "appearance": "By inquiry",
    "physicalState": "inquiry",
    "capacity": "By inquiry",
    "status": "Made-to-order",
    "price": "About RMB 3,000,000/t",
    "cid": 44558105,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/44558105/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/44558105",
    "properties": {
      "formula": "C6H3ClFNO2",
      "molecularWeight": "175.54",
      "exactMass": "174.9836342",
      "iupac": "2-chloro-5-fluoropyridine-4-carboxylic acid",
      "smiles": "C1=C(C(=CN=C1Cl)F)C(=O)O",
      "xlogp": 1.4,
      "tpsa": 50.2,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 167
    }
  },
  {
    "no": 11,
    "name": "7-Chloro-1-cyclopropyl-6-fluoro-4-oxo-1,4-dihydro-1,8-naphthyridine-3-carboxylic acid",
    "cas": "100361-18-0",
    "purity": "99%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 1,900,000/t",
    "cid": 11055142,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/11055142/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/11055142",
    "properties": {
      "formula": "C12H8ClFN2O3",
      "molecularWeight": "282.65",
      "exactMass": "282.0207480",
      "iupac": "7-chloro-1-cyclopropyl-6-fluoro-4-oxo-1,8-naphthyridine-3-carboxylic acid",
      "smiles": "C1CC1N2C=C(C(=O)C3=CC(=C(N=C32)Cl)F)C(=O)O",
      "xlogp": 3.4,
      "tpsa": 70.5,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 6,
      "rotatableBondCount": 2,
      "heavyAtomCount": 19,
      "complexity": 466
    }
  },
  {
    "no": 12,
    "name": "Ethyl 7-chloro-1-cyclopropyl-6-fluoro-4-oxo-1,4-dihydro-1,8-naphthyridine-3-carboxylate",
    "cas": "96568-07-9",
    "purity": "99%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 1,700,000/t",
    "cid": 11722954,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/11722954/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/11722954",
    "properties": {
      "formula": "C14H12ClFN2O3",
      "molecularWeight": "310.71",
      "exactMass": "310.0520481",
      "iupac": "ethyl 7-chloro-1-cyclopropyl-6-fluoro-4-oxo-1,8-naphthyridine-3-carboxylate",
      "smiles": "CCOC(=O)C1=CN(C2=NC(=C(C=C2C1=O)F)Cl)C3CC3",
      "xlogp": 3,
      "tpsa": 59.5,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 6,
      "rotatableBondCount": 4,
      "heavyAtomCount": 21,
      "complexity": 495
    }
  },
  {
    "no": 13,
    "name": "7-Chloro-1-(2,4-difluorophenyl)-6-fluoro-4-oxo-1,4-dihydro-1,8-naphthyridine-3-carboxylic acid",
    "cas": "100492-04-4",
    "purity": "99%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 1,760,000/t",
    "cid": 10546084,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/10546084/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/10546084",
    "properties": {
      "formula": "C15H6ClF3N2O3",
      "molecularWeight": "354.67",
      "exactMass": "354.0019042",
      "iupac": "7-chloro-1-(2,4-difluorophenyl)-6-fluoro-4-oxo-1,8-naphthyridine-3-carboxylic acid",
      "smiles": "C1=CC(=C(C=C1F)F)N2C=C(C(=O)C3=CC(=C(N=C32)Cl)F)C(=O)O",
      "xlogp": 3.9,
      "tpsa": 70.5,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 8,
      "rotatableBondCount": 2,
      "heavyAtomCount": 24,
      "complexity": 576
    }
  },
  {
    "no": 14,
    "name": "Ethyl 7-chloro-1-(2,4-difluorophenyl)-6-fluoro-1,4-dihydro-4-oxo-1,8-naphthyridine-3-carboxylate",
    "cas": "100491-29-0",
    "purity": "99%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 1,600,000/t",
    "cid": 1268243,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/1268243/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/1268243",
    "properties": {
      "formula": "C17H10ClF3N2O3",
      "molecularWeight": "382.7",
      "exactMass": "382.0332044",
      "iupac": "ethyl 7-chloro-1-(2,4-difluorophenyl)-6-fluoro-4-oxo-1,8-naphthyridine-3-carboxylate",
      "smiles": "CCOC(=O)C1=CN(C2=NC(=C(C=C2C1=O)F)Cl)C3=C(C=C(C=C3)F)F",
      "xlogp": 4,
      "tpsa": 59.5,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 8,
      "rotatableBondCount": 4,
      "heavyAtomCount": 26,
      "complexity": 606
    }
  },
  {
    "no": 15,
    "name": "5-Amino-2-methylbenzoic acid",
    "cas": "2840-04-2",
    "purity": "98%",
    "appearance": "Off-white crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "Made-to-order",
    "price": "RMB 500,000/t",
    "cid": 10374614,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/10374614/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/10374614",
    "properties": {
      "formula": "C8H9NO2",
      "molecularWeight": "151.16",
      "exactMass": "151.063328530",
      "iupac": "5-amino-2-methylbenzoic acid",
      "smiles": "CC1=C(C=C(C=C1)N)C(=O)O",
      "xlogp": 1.1,
      "tpsa": 63.3,
      "hBondDonorCount": 2,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 158
    }
  },
  {
    "no": 16,
    "name": "5-Bromo-2-methylbenzoic acid",
    "cas": "79669-49-1",
    "purity": "98%",
    "appearance": "Off-white to orange-red crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "In stock",
    "price": "RMB 200,000/t",
    "cid": 346004,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/346004/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/346004",
    "properties": {
      "formula": "C8H7BrO2",
      "molecularWeight": "215.04",
      "exactMass": "213.96294",
      "iupac": "5-bromo-2-methylbenzoic acid",
      "smiles": "CC1=C(C=C(C=C1)Br)C(=O)O",
      "xlogp": 2.5,
      "tpsa": 37.3,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 2,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 158
    }
  },
  {
    "no": 17,
    "name": "5-Chloro-2-methylbenzoic acid",
    "cas": "7499-06-1",
    "purity": "98%",
    "appearance": "Off-white to orange-red crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "Made-to-order",
    "price": "RMB 1,000,000/t",
    "cid": 82009,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/82009/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/82009",
    "properties": {
      "formula": "C8H7ClO2",
      "molecularWeight": "170.59",
      "exactMass": "170.0134572",
      "iupac": "5-chloro-2-methylbenzoic acid",
      "smiles": "CC1=C(C=C(C=C1)Cl)C(=O)O",
      "xlogp": 2.4,
      "tpsa": 37.3,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 2,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 158
    }
  },
  {
    "no": 18,
    "name": "5-Hydroxy-2-methylbenzoic acid",
    "cas": "578-22-3",
    "purity": "98%",
    "appearance": "Off-white crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "Made-to-order",
    "price": "RMB 1,200,000/t",
    "cid": 235188,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/235188/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/235188",
    "properties": {
      "formula": "C8H8O3",
      "molecularWeight": "152.15",
      "exactMass": "152.047344113",
      "iupac": "5-hydroxy-2-methylbenzoic acid",
      "smiles": "CC1=C(C=C(C=C1)O)C(=O)O",
      "xlogp": 1.5,
      "tpsa": 57.5,
      "hBondDonorCount": 2,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 155
    }
  },
  {
    "no": 19,
    "name": "4-Nitro-o-toluic acid",
    "cas": "1975-51-5",
    "purity": "98%",
    "appearance": "Pale yellow crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "In stock",
    "price": "RMB 600,000/t",
    "cid": 74790,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/74790/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/74790",
    "properties": {
      "formula": "C8H7NO4",
      "molecularWeight": "181.15",
      "exactMass": "181.03750770",
      "iupac": "2-methyl-4-nitrobenzoic acid",
      "smiles": "CC1=C(C=CC(=C1)[N+](=O)[O-])C(=O)O",
      "xlogp": 1.6,
      "tpsa": 83.1,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 1,
      "heavyAtomCount": 13,
      "complexity": 223
    }
  },
  {
    "no": 20,
    "name": "4-Amino-2-methylbenzoic acid",
    "cas": "2486-75-1",
    "purity": "98%",
    "appearance": "Off-white to pale yellow powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "In stock",
    "price": "RMB 900,000/t",
    "cid": 241632,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/241632/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/241632",
    "properties": {
      "formula": "C8H9NO2",
      "molecularWeight": "151.16",
      "exactMass": "151.063328530",
      "iupac": "4-amino-2-methylbenzoic acid",
      "smiles": "CC1=C(C=CC(=C1)N)C(=O)O",
      "xlogp": 1.1,
      "tpsa": 63.3,
      "hBondDonorCount": 2,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 158
    }
  },
  {
    "no": 21,
    "name": "4-Bromo-2-methylbenzoic acid",
    "cas": "68837-59-2",
    "purity": "98%",
    "appearance": "Off-white to orange-red crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "In stock",
    "price": "RMB 950,000/t",
    "cid": 99570,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/99570/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/99570",
    "properties": {
      "formula": "C8H7BrO2",
      "molecularWeight": "215.04",
      "exactMass": "213.96294",
      "iupac": "4-bromo-2-methylbenzoic acid",
      "smiles": "CC1=C(C=CC(=C1)Br)C(=O)O",
      "xlogp": 2.5,
      "tpsa": 37.3,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 2,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 158
    }
  },
  {
    "no": 22,
    "name": "4-Chloro-2-methylbenzoic acid",
    "cas": "7499-07-2",
    "purity": "98%",
    "appearance": "Off-white to orange-red crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "In stock",
    "price": "RMB 3,500,000/t",
    "cid": 348269,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/348269/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/348269",
    "properties": {
      "formula": "C8H7ClO2",
      "molecularWeight": "170.59",
      "exactMass": "170.0134572",
      "iupac": "4-chloro-2-methylbenzoic acid",
      "smiles": "CC1=C(C=CC(=C1)Cl)C(=O)O",
      "xlogp": 2.4,
      "tpsa": 37.3,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 2,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 158
    }
  },
  {
    "no": 23,
    "name": "4-Hydroxy-o-toluic acid",
    "cas": "578-39-2",
    "purity": "98%",
    "appearance": "Off-white to orange-red crystalline powder",
    "physicalState": "solid",
    "capacity": "By inquiry",
    "status": "Made-to-order",
    "price": "RMB 3,500,000/t",
    "cid": 68475,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/68475/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/68475",
    "properties": {
      "formula": "C8H8O3",
      "molecularWeight": "152.15",
      "exactMass": "152.047344113",
      "iupac": "4-hydroxy-2-methylbenzoic acid",
      "smiles": "CC1=C(C=CC(=C1)O)C(=O)O",
      "xlogp": 1.5,
      "tpsa": 57.5,
      "hBondDonorCount": 2,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 1,
      "heavyAtomCount": 11,
      "complexity": 155
    }
  },
  {
    "no": 24,
    "name": "Methyl 4-Chloropicolinate",
    "cas": "24484-93-3",
    "purity": "98%",
    "appearance": "Pale yellow powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 600,000/t",
    "cid": 820890,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/820890/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/820890",
    "properties": {
      "formula": "C7H6ClNO2",
      "molecularWeight": "171.58",
      "exactMass": "171.0087061",
      "iupac": "methyl 4-chloropyridine-2-carboxylate",
      "smiles": "COC(=O)C1=NC=CC(=C1)Cl",
      "xlogp": 1.7,
      "tpsa": 39.2,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 2,
      "heavyAtomCount": 11,
      "complexity": 151
    }
  },
  {
    "no": 25,
    "name": "2-Amino-4-chloropyridine",
    "cas": "19798-80-2",
    "purity": "98%",
    "appearance": "Pale yellow powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 1,100,000/t",
    "cid": 581866,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/581866/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/581866",
    "properties": {
      "formula": "C5H5ClN2",
      "molecularWeight": "128.56",
      "exactMass": "128.0141259",
      "iupac": "4-chloropyridin-2-amine",
      "smiles": "C1=CN=C(C=C1Cl)N",
      "xlogp": 1.1,
      "tpsa": 38.9,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 2,
      "rotatableBondCount": 0,
      "heavyAtomCount": 8,
      "complexity": 76
    }
  },
  {
    "no": 26,
    "name": "2-Aminopyridin-4-ol",
    "cas": "33631-05-9",
    "purity": "99%",
    "appearance": "Off-white powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 1,100,000/t",
    "cid": 820936,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/820936/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/820936",
    "properties": {
      "formula": "C5H6N2O",
      "molecularWeight": "110.11",
      "exactMass": "110.048012819",
      "iupac": "2-amino-1H-pyridin-4-one",
      "smiles": "C1=CNC(=CC1=O)N",
      "xlogp": -0.3,
      "tpsa": 55.1,
      "hBondDonorCount": 2,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 0,
      "heavyAtomCount": 8,
      "complexity": 169
    }
  },
  {
    "no": 27,
    "name": "(1,2,4)Triazolo(1,5-a)pyridin-7-ol",
    "cas": "1033810-70-6",
    "purity": "99%",
    "appearance": "Off-white to pale yellow crystalline powder",
    "physicalState": "solid",
    "capacity": "2 t",
    "status": "In stock",
    "price": "RMB 4,500,000/t",
    "cid": 66937011,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/66937011/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/66937011",
    "properties": {
      "formula": "C6H5N3O",
      "molecularWeight": "135.12",
      "exactMass": "135.043261791",
      "iupac": "3H-[1,2,4]triazolo[1,5-a]pyridin-7-one",
      "smiles": "C1=CN2C(=CC1=O)N=CN2",
      "xlogp": -0.3,
      "tpsa": 44.7,
      "hBondDonorCount": 1,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 0,
      "heavyAtomCount": 10,
      "complexity": 264
    }
  },
  {
    "no": 28,
    "name": "3-Ethylbicyclo[3.2.0]hept-3-en-6-one",
    "cas": "1235479-59-0",
    "purity": "99%",
    "appearance": "By inquiry",
    "physicalState": "inquiry",
    "capacity": "2 t",
    "status": "Made-to-order",
    "price": "RMB 1,000,000/t",
    "cid": 76285463,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/76285463/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/76285463",
    "properties": {
      "formula": "C9H12O",
      "molecularWeight": "136.19",
      "exactMass": "136.088815002",
      "iupac": "3-ethylbicyclo[3.2.0]hept-3-en-6-one",
      "smiles": "CCC1=CC2C(C1)CC2=O",
      "xlogp": 1.2,
      "tpsa": 17.1,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 1,
      "rotatableBondCount": 1,
      "heavyAtomCount": 10,
      "complexity": 203
    }
  },
  {
    "no": 29,
    "name": "7-Benzyl-2,4-dichloro-5,6,7,8-tetrahydropyrido(3,4-d)pyrimidine",
    "cas": "1059735-34-0",
    "purity": "99%",
    "appearance": "By inquiry",
    "physicalState": "inquiry",
    "capacity": "2 t",
    "status": "Made-to-order",
    "price": "RMB 4,500,000/t",
    "cid": 46839894,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/46839894/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/46839894",
    "properties": {
      "formula": "C14H13Cl2N3",
      "molecularWeight": "294.2",
      "exactMass": "293.0486528",
      "iupac": "7-benzyl-2,4-dichloro-6,8-dihydro-5H-pyrido[3,4-d]pyrimidine",
      "smiles": "C1CN(CC2=C1C(=NC(=N2)Cl)Cl)CC3=CC=CC=C3",
      "xlogp": 3.5,
      "tpsa": 29,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 3,
      "rotatableBondCount": 2,
      "heavyAtomCount": 19,
      "complexity": 296
    }
  },
  {
    "no": 30,
    "name": "4-Piperidinecarboxylic acid, 1-(8-chloro-1-naphthalenyl)-3-oxo-, methyl ester",
    "cas": "2898538-56-0",
    "purity": "99%",
    "appearance": "By inquiry",
    "physicalState": "inquiry",
    "capacity": "2 t",
    "status": "Made-to-order",
    "price": "RMB 3,500,000/t",
    "cid": 170910290,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/170910290/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/170910290",
    "properties": {
      "formula": "C17H16ClNO3",
      "molecularWeight": "317.8",
      "exactMass": "317.0818711",
      "iupac": "methyl 1-(8-chloronaphthalen-1-yl)-3-oxopiperidine-4-carboxylate",
      "smiles": "COC(=O)C1CCN(CC1=O)C2=CC=CC3=C2C(=CC=C3)Cl",
      "xlogp": 4,
      "tpsa": 46.6,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 3,
      "heavyAtomCount": 22,
      "complexity": 442
    }
  },
  {
    "no": 31,
    "name": "Methyl dimethoxyacetate",
    "cas": "89-91-8",
    "purity": "99%",
    "appearance": "By inquiry",
    "physicalState": "inquiry",
    "capacity": "10 t",
    "status": "In stock",
    "price": "RMB 350,000/t",
    "cid": 66647,
    "structureImage": "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/66647/PNG?image_size=300x300",
    "pubchemUrl": "https://pubchem.ncbi.nlm.nih.gov/compound/66647",
    "properties": {
      "formula": "C5H10O4",
      "molecularWeight": "134.13",
      "exactMass": "134.05790880",
      "iupac": "methyl 2,2-dimethoxyacetate",
      "smiles": "COC(C(=O)OC)OC",
      "xlogp": 0,
      "tpsa": 44.8,
      "hBondDonorCount": 0,
      "hBondAcceptorCount": 4,
      "rotatableBondCount": 4,
      "heavyAtomCount": 9,
      "complexity": 87
    }
  }
];
